### ISSUE TITLE
English first?

### ISSUE THREAD

**Issue by manudeli** [toss/overlay-kit#12]
https://github.com/toss/overlay-kit/blob/f377f72bffa36d533e284102749e00f6dfc03d92/packages/src/utils/create-use-external-events.ts#L12-L13

**Comment by jungpaeng** [comment]
It appears that Toss’s frontend open-source projects, except for es-hangul, communicate in English. Therefore, it would be beneficial for overlay-kit to follow this practice as well.

However, the comments and descriptions in test cases are currently written in Korean, which disrupts consistency. We will work on converting these to English to maintain uniformity.
