### ISSUE TITLE
overlay의 내부 구현 코드를 보려면 어떻게 해야 하나요??

### ISSUE THREAD

**Issue by wo-o29** [toss/overlay-kit#20]
안녕하세요! <a href="https://overlay-kit.slash.page/ko/api/overlay.html">overlay 객체 공식 문서</a>를 읽고 `overlay.open(...)` 콜백 함수의 `open`, `close`, `unmount` 와 같은 프로퍼티들이 어떻게 동작하는지 내부 구현을 보고 싶어서 모듈 파일을 확인해봤는데 컴파일되어 있는 결과물만 있는 것 같은데 어떻게 하면 내부 구현 코드를 확인할 수 있나요??

**Comment by po4tion** [comment]
[https://github.com/toss/overlay-kit/tree/main/packages](https://github.com/toss/overlay-kit/tree/main/packages)
이곳에서 확인할 수 있습니다.

**Comment by wo-o29** [comment]
> https://github.com/toss/overlay-kit/tree/main/packages 이곳에서 확인할 수 있습니다.

답변 감사합니다!! 👍👍👍
