### ISSUE TITLE
`overlay.close` and `overlay.unmount`'s argument, parameter name matching

### ISSUE THREAD

**Issue by jgjgill** [toss/overlay-kit#38]
When I read docs, `overlay.close` and `overlay.unmount` arguments are `overlayId`.

<img width="773" alt="스크린샷 2024-07-05 오후 6 55 52" src="https://github.com/toss/overlay-kit/assets/79239852/cc3f69e1-addf-4bbd-917e-0889707ac542">

But in the code, they are `id` as parameters.

[**events.ts**](https://github.dev/toss/overlay-kit/blob/a130e77524b42919b1e86450b0d7716702358f93/packages/src/event.ts#L23-L27)

<img width="485" alt="스크린샷 2024-07-05 오후 7 01 24" src="https://github.com/toss/overlay-kit/assets/79239852/7dc843d0-de9d-4a6c-a0c4-1728556738c5">

I think it would be more consistent if it was `overlayId`.
what do you think?

**Comment by jungpaeng** [comment]
I don’t think the issue you pointed out significantly affects the usability of the library. 
However, I believe that small details like these contribute to the overall quality. Therefore, I agree that it would be better to align with the documentation for consistency.

I will make the changes. Thank you for pointing this out.

**Comment by jgjgill** [comment]
> I don’t think the issue you pointed out significantly affects the usability of the library.

저도 동의합니다. 테스트 코드나 문서가 아니라 기능 코드가 변경된다고 생각했기 때문에 사소한 세부 사항임에도 불구하고 바로 PR을 작성하는 대신 이슈를 만들었습니다. 😂
If you haven't worked on it yet, can I write a PR and contribute to it? 🧐

**Comment by jungpaeng** [comment]
> If you haven't worked on it yet, can I write a PR and contribute to it? 🧐

Sure! Contributing through a PR would be very helpful.
Thank you!

**Comment by jgjgill** [comment]
Ok! I'm learning a lot thanks to you! 👍
