### ISSUE TITLE
Planned Support for React 16.8 and 17

### ISSUE THREAD

**Issue by jungpaeng** [toss/overlay-kit#43]
We are planning to add support for both React 16.8 and React 17 versions in this project. This upcoming update will ensure compatibility and provide flexibility for developers using different versions of React in their projects.

**Comment by manudeli** [comment]
In my opinion https://www.npmjs.com/package/use-sync-external-store could be solution

**Comment by jungpaeng** [comment]
I’m delaying work until issue #55 is resolved.
